### ISSUE TITLE
Instruction lookup table is insufficient

### ISSUE THREAD

**Issue by blue-devil** [hanicraft/Universal-C-Decompiler#1]
This is the file i am trying to decompile: [pwndr](https://gofile.io/d/Dv0UNE)

I only want to decompile main function so I run this:
```
python Decompile.py -f pwndr -o pwndr.c -b 11F7 -e 14f0
Instruction not found...
Quitting...
```

Then I have realized that this look up table is insufficient:
```python
        # Instruction lookup
        self.cinstr = {
            'mov' : mov,
            'movzx' : movzx,
            'movsx' : movzx,
            'cdqe' : cdqe,
            'sub' : sub,
            'add' : add,
            'inc' : inc,
            'dec' : dec,
            'cmp' : cmp,
            'jmp' : jmp,
            'jne' : jne,
            'je'  : je,
            'jnb' : jnb,
            'jb'  : jb,
            'jbe' : jbe
        }
```

**Comment by hanicraft** [comment]
hi
we this is uncompiled source code of first version of decompiler
so it might not work well
please download and use executable file from releases
also im working to make decompiler also be able to decompile dlls and 64bit files
thank you
